### ISSUE TITLE
width/rtm

### ISSUE THREAD

**Issue by jordens** [m-labs/metlino#2]
Usually an MCH is single-width and would thus not be able to connect to "its" RTM.
The root Metlino needs a reference frequency -- 100 MHz -- to seed the DRTIO timing tree. Should we make Metlino double-width and somehow connect it to its RTM (that also drives the rf backplane clocking and thus has the reference frequency -- 100 MHz -- on it)? Or should the root Metlino always get its reference through its AMC-side panel? The latter would have the advantage that root/satellite Metlinos do not already require a double-width rack with RTMs and rf backplane and would also work in other racks with smaller hardware.

@jbqubit @gkasprow @jmizrahi

**Comment by jordens** [comment]
It's not clear to me what we need that 100 MHz clock module on Metlino and the 100 MHz clock distribution for. Every Sayma can and will get an excellent clock from their RTM. And for all kinds of booting, testing, and stand-alone operation, we'd want a simple oscillator on Sayma anyway.

**Comment by sbourdeauducq** [comment]
> We may use RTM in the future, but not necessarily now.

As per my email: 
https://ssl.serverraum.org/lists-archive/artiq/2016-September/001007.html
it appears necessary to transmit the same 100MHz clock on both RTM (RF backplane) and AMC sides.

**Comment by jordens** [comment]
This issue was moved to m-labs/sinara#36
